### ISSUE TITLE
Add favicon to site

### ISSUE THREAD

**Issue by deld** [DSCoalition/digitalservicescoalition.org#3]
need a favicon. 

<img width="345" alt="screenshot 2019-01-29 13 28 32" src="https://user-images.githubusercontent.com/3333445/51931032-e510e880-23c9-11e9-98f7-9ff729e8f8c8.png">

**Comment by yuansun235** [comment]
![favicon](https://user-images.githubusercontent.com/20797752/52011411-d3872800-2512-11e9-875b-3aacad77c6e7.png)

**Comment by deld** [comment]
still getting a 404 
![screenshot 2019-01-30 16 09 55](https://user-images.githubusercontent.com/3333445/52012803-8327b000-24a9-11e9-948b-de307b19543c.png)

**Comment by deld** [comment]
fixed
