### ISSUE TITLE
Site is slow on initial load due to incorrect iframe

### ISSUE THREAD

**Issue by deld** [DSCoalition/digitalservicescoalition.org#4]
site takes a while to load the first time.

**Comment by bhalt** [comment]
This is due to the iframe on http://digitalservicescoalition.org that displays https://dscoalition.github.io/digitalservicescoalition.org -- this should not be an iframe.

**Comment by deld** [comment]
can you verify this fix @bhalt ?

**Comment by bhalt** [comment]
Getting a 404 so can't tell..
