### ISSUE TITLE
URL routing not updating address bar due to incorrect iframe

### ISSUE THREAD

**Issue by deld** [DSCoalition/digitalservicescoalition.org#5]
Issue with the router history. It works great on local, but on the web if you click the different pages, it doesn't update the URL. And if you go to a specific route in the browser, such as http://digitalservicescoalition.org/mission , it redirects to the homepage.

To reproduce:

Go to http://digitalservicescoalition.org/ and click any of the menu options and the address bar doesn't change

If you go to https://dscoalition.github.io/digitalservicescoalition.org the actual github pages url and click around it does.

**Comment by bhalt** [comment]
This is due to the iframe on http://digitalservicescoalition.org that displays https://dscoalition.github.io/digitalservicescoalition.org -- this should not be an iframe.

**Comment by deld** [comment]
Also note I updates github pages to use a custom domain of digitalservicescoalition.org now.

**Comment by yuansun235** [comment]
This is related to DNS.

- Create DNS entries
1. A Records for @
2. Create a CNAME record to point www.digitalservicescoalition.org to dscoalition.github.io

- Confirm DNS entries
1. Confirm A records by running dig +noall +answer digitalservicescoalition.org. 
    It should return the four 185.x.x.x IP addresses you entered.
2. Confirms CNAME record by running dig digitalservicescoalition.org +nostats +nocomments +nocmd. 
    It should return a CNAME   dscoalition.github.io

**Comment by deld** [comment]
I've updated the cname www record ...the other A records have already been set @yuansun235

**Comment by deld** [comment]
I performed both of these (please verify on your end as well)

> Confirm A records by running dig +noall +answer digitalservicescoalition.org.
> It should return the four 185.x.x.x IP addresses you entered.
> Confirms CNAME record by running dig digitalservicescoalition.org +nostats +nocomments +nocmd.
> It should return a CNAME dscoalition.github.io

Both resolve to the same thing.  the 185.x.x.x IP addresses.

**Comment by deld** [comment]
Something is wrong with the code.....see the console: 
![screenshot 2019-01-30 21 11 28](https://user-images.githubusercontent.com/3333445/52025793-b3844400-24d3-11e9-8e4a-d3110d69c4cf.png)

**Comment by deld** [comment]
this is fixed now, was an issue in the config...fixed with this https://github.com/DSCoalition/digitalservicescoalition.org/commit/40850639c84ec01ce6bac524ebd54534d76e8a39
