### ISSUE TITLE
imagage overlap bug

### ISSUE THREAD

**Issue by deld** [DSCoalition/digitalservicescoalition.org#6]
Image is covering the text 
![screenshot 2019-01-31 06 08 01](https://user-images.githubusercontent.com/3333445/52050466-9f196900-251e-11e9-92de-d45e794f7aa8.png)

**Comment by bhalt** [comment]
I don't get this on that page at any breakpoint. What browser / setup is this on? Have you refreshed recently? Could be from the iframe.

**Comment by deld** [comment]
confirmed, its gone now @bhalt ....closing this issue
