### ISSUE TITLE
Update DSC Board & Officers

### ISSUE THREAD

**Issue by Discocowboy** [DSCoalition/digitalservicescoalition.org#79]
https://digitalservicescoalition.org/#/story

Remove Sarah Ruggless, Marc Jones, and Tyra Blew

Add/Replace with
- Stephanie Chin, Fearless, Board Member
![stephaniechin](https://user-images.githubusercontent.com/12417007/184007032-541f1ca9-2a49-4192-bde7-028c78bd355e.jpg)

- Mike Gifford, CivicActions, Board Member
![mikegifford](https://user-images.githubusercontent.com/12417007/184006969-094de68a-597b-4f5b-b0a5-e296446a4ee7.jpg)

- Carl Bunche, Flexion, Treasurer
![carlbunche](https://user-images.githubusercontent.com/12417007/184006986-c60e8d16-b34d-4e45-89d5-61d9b86927ad.png)

- Tabby Farrar, MediaBarn, Secretary
![tabbyfarrar](https://user-images.githubusercontent.com/12417007/184006857-90228fd4-af9e-428b-956c-6cd5f3f37109.jpg) 

May need to go with a layout of 3 rows of 3

**Comment by SeaJerry** [comment]
@Discocowboy, Not quite sure who is who. Can you add their name underneath their photo? Thanks!

**Comment by Discocowboy** [comment]
@SeaJerry updated, I also have the images associated with their names

**Comment by SeaJerry** [comment]
Awesome, Thanks! @Discocowboy
