### ISSUE TITLE
Routing is broken on fresh load of page (push state)

### ISSUE THREAD

**Issue by bengm** [DSCoalition/digitalservicescoalition.org#8]

**Comment by bengm** [comment]
To replicate, go straight to any non-home page, e.g.:
https://digitalservicescoalition.org/mission
- Or - Navigate to a non-home page and refresh browser.

**Comment by bengm** [comment]
[`hash-routing`](https://github.com/DSCoalition/digitalservicescoalition.org/tree/feature/hash-routing) branch implements one type of fix to this issue.

**Comment by bengm** [comment]
Another fix would be converting the app to Jekyll (static site generator).

**Comment by deld** [comment]
confirming fix, closing issue
