### ISSUE TITLE
Announcement Update

### ISSUE THREAD

**Issue by Discocowboy** [DSCoalition/digitalservicescoalition.org#83]
https://digitalservicescoalition.org/#/membership

In green box

Announcement
We're not accepting new member applications at this time.
If you want to get on our mailing list, contact us at [membership@digitalservicescoalition.org](mailto:membership@digitalserviescoalition.org)

**Comment by SeaJerry** [comment]
@Discocowboy, Did you want the email to be a link or plain text?

**Comment by Discocowboy** [comment]
a link would be ideal
